export const verbs = [
    {infinitief: "aandoen", imperfectum: ["deed aan", "deden aan"], perfectum: ["hebben","aangedaan"], translation: "to do"},
    {infinitief: "aankomen", imperfectum: ["kwam aan", "kwamen aan"], perfectum: ["zijn","aangekomen"], translation: "to come"},
    {infinitief: "afwassen", imperfectum: ["waste af", "wasten af"], perfectum: ["hebben", "afgewassen"], translation: "to wash"},
    {infinitief: "bakken", imperfectum: ["bakte", "bakten"], perfectum: ["hebben", "gebakken"], translation: "baking"},
    {infinitief: "beginnen", imperfectum: ["begon", "begonnen"], perfectum: ["zijn", "gebegonnen"], translation: "to start"},
    {infinitief: "begrijpen", imperfectum: ["begreep", "begrepen"], perfectum: ["hebben", "begrepen"], translation: "to understand"},
    {infinitief: "behangen", imperfectum: ["behing", "behingen"], perfectum: ["hebben", "behangen"], translation: "to hang"},
    {infinitief: "bewegen", imperfectum: ["bewoog", "bewogen"], perfectum: ["hebben", "bewogen"], translation: "to move"},
    {infinitief: "bezoeken", imperfectum: ["bezocht", "bezochten"], perfectum: ["hebben", "bezocht"], translation: "to visit"},
    {infinitief: "bijten", imperfectum: ["beet", "beten"], perfectum: ["hebben", "gebeten"], translation: "to bite"},
    {infinitief: "blazen", imperfectum: ["blies", "bliezen"], perfectum: ["hebben", "geblazen"], translation: "to blow"},
    {infinitief: "blijven", imperfectum: ["bleef", "bleven"], perfectum: ["zijn", "gebleven"], translation: "to stay"},
    {infinitief: "breken", imperfectum: ["brak", "braken"], perfectum: ["hebben", "gebroken"], translation: "to break"},
    {infinitief: "brengen", imperfectum: ["bracht", "brachten"], perfectum: ["hebben", "gebracht"], translation: "to take"},
    {infinitief: "denken", imperfectum: ["dacht", "dachten"], perfectum: ["hebben", "gedacht"], translation: "to think"},
    {infinitief: "doen", imperfectum: ["deed", "deden"], perfectum: ["hebben", "gedaan"], translation: "doing"},
    {infinitief: "dragen", imperfectum: ["droeg", "droegen"], perfectum: ["hebben", "gedragen"], translation: "to wear"},
    {infinitief: "drinken", imperfectum: ["dronk", "dronken"], perfectum: ["hebben", "gedronken"], translation: "to drink"},
    {infinitief: "eten", imperfectum: ["at", "aten"], perfectum: ["hebben", "gegeten"], translation: "to eat"},
    {infinitief: "gaan", imperfectum: ["ging", "gingen"], perfectum: ["zijn", "gegaan"], translation: "to go"},
    {infinitief: "genezen", imperfectum: ["genas", "genazen"], perfectum: ["hebben", "genezen"], translation: "to cure"},
    {infinitief: "geven", imperfectum: ["gaf", "gaven"], perfectum: ["hebben", "gegeven"], translation: "to give"},
    {infinitief: "gieten", imperfectum: ["goot", "goten"], perfectum: ["hebben", "gegoten"], translation: "to pour"},
    {infinitief: "hangen", imperfectum: ["hing", "hingen"], perfectum: ["hebben", "gehangen"], translation: "to hang"},
    {infinitief: "hebben", imperfectum: ["had", "hadden"], perfectum: ["hebben", "gehad"], translation: "to have"},
    {infinitief: "helpen", imperfectum: ["hielp", "hielpen"], perfectum: ["hebben", "geholpen"], translation: "to help"},
    {infinitief: "houden(van)", imperfectum: ["hield", "hielden"], perfectum: ["hebben", "gehouden"], translation: "to love"},
    {infinitief: "innemen", imperfectum: ["nam in", "namen in"], perfectum: ["hebben", "ingenomen"], translation: "to take"},
    {infinitief: "kiezen", imperfectum: ["koos", "kozen"], perfectum: ["hebben", "gekozen"], translation: "to choose"},
    {infinitief: "kijken", imperfectum: ["keek", "keken"], perfectum: ["hebben", "gekeken"], translation: "to look"},
    {infinitief: "komen", imperfectum: ["kwam", "kwamen"], perfectum: ["zijn", "gekomen"], translation: "to come"},
    {infinitief: "kopen", imperfectum: ["kocht", "kochten"], perfectum: ["hebben", "gekocht"], translation: "to buy"},
    {infinitief: "krijgen", imperfectum: ["kreeg", "kregen"], perfectum: ["hebben", "gekregen"], translation: "to get"},
    {infinitief: "kunnen", imperfectum: ["kon", "konden"], perfectum: ["hebben", "gekund"], translation: "be able to"},
    {infinitief: "laten", imperfectum: ["liet", "lieten"], perfectum: ["hebben", "gelaten"], translation: "to leave"},
    {infinitief: "lezen", imperfectum: ["las", "lazen"], perfectum: ["hebben", "gelezen"], translation: "read"},
    {infinitief: "liggen", imperfectum: ["lag", "lagen"], perfectum: ["hebben", "gelegen"], translation: "lie"},
    {infinitief: "lopen", imperfectum: ["liep", "liepen"], perfectum: ["hebben/zijn", "gelopen"], translation: "to walk"},
    {infinitief: "meenemen", imperfectum: ["nam mee", "namen mee"], perfectum: ["hebben", "meegenomen"], translation: "take"},
    {infinitief: "moeten", imperfectum: ["moest", "moesten"], perfectum: ["hebben", "gemoeten"], translation: "must"},
    {infinitief: "mogen", imperfectum: ["mocht", "mochten"], perfectum: ["hebben", "gemogen"], translation: "to be allowed to"},
    {infinitief: "nakijken", imperfectum: ["keek na", "keken na"], perfectum: ["hebben", "nagekeken"], translation: "check"},
    {infinitief: "nemen", imperfectum: ["nom", "nomen"], perfectum: ["hebben", "genomen"], translation: "to take"},
    {infinitief: "onderzoeken", imperfectum: ["onderzocht", "onderzochten"], perfectum: ["hebben", "onderzocht"], translation: "to research"},
    {infinitief: "ontbijten", imperfectum: ["ontbeet", "ontbeten"], perfectum: ["hebben", "ontbeten"], translation: "having breakfast"},
    {infinitief: "opstaan", imperfectum: ["stond op", "stonden op"], perfectum: ["hebben", "opgestaan"], translation: "to get up"},


// page two

    {infinitief: "oversteken", imperfectum: ["stak over", "staken"], perfectum: ["zijn", "overgestoken"], translation: "to cross"},
    {infinitief: "rijden", imperfectum: ["reed", "reden"], perfectum: ["hebben/zijn", "gereden"], translation: "to ride"},
    {infinitief: "roepen", imperfectum: ["riep", "riepen"], perfectum: ["hebben", "geroepen"], translation: "call"},
    {infinitief: "scheiden", imperfectum: ["scheidde", "scheidden"], perfectum: ["zijn", "gescheiden"], translation: "to divorce"},
    {infinitief: "schijnen", imperfectum: ["scheen", "scheen"], perfectum: ["zijn", "geschenen"], translation: "to shine"},
    {infinitief: "schrijven", imperfectum: ["schreef", "schreven"], perfectum: ["hebben", "geschreven"], translation: "to write"},
    {infinitief: "slapen", imperfectum: ["sliep", "sliepen"], perfectum: ["hebben", "geslapen"], translation: "to sleep"},
    {infinitief: "sluiten", imperfectum: ["sloot", "sloten"], perfectum: ["hebben", "gesloten"], translation: "to close"},
    {infinitief: "snijden", imperfectum: ["sneed", "sneden"], perfectum: ["hebben", "gesneden"], translation: "to cut"},
    {infinitief: "spreken", imperfectum: ["sprak", "spraken"], perfectum: ["hebben", "gesproken"], translation: "to speak"},
    {infinitief: "springen", imperfectum: ["sprong", "sprongen"], perfectum: ["hebben", "gesprongen"], translation: "to jump"},
    {infinitief: "staan", imperfectum: ["stond", "stonden"], perfectum: ["hebben", "gestaan"], translation: "to stand"},
    {infinitief: "steken", imperfectum: ["stak", "staken"], perfectum: ["hebben", "gestoken"], translation: "stiches"},
    {infinitief: "sterven", imperfectum: ["stierf", "stierven"], perfectum: ["zijn", "gestorven"], translation: "to die"},
    {infinitief: "strijken", imperfectum: ["streek", "streken"], perfectum: ["hebben", "gestreken"], translation: "to iron"},
    {infinitief: "treffen", imperfectum: ["trof", "troffen"], perfectum: ["hebben", "getroffen"], translation: "to meet"},
    {infinitief: "trekken", imperfectum: ["trok", "trokken"], perfectum: ["hebben", "getrokken"], translation: "to pull"},
    {infinitief: "uitdoen", imperfectum: ["deed uit", "deden uit"], perfectum: ["hebben", "uitgedaan"], translation: "put out"},
    {infinitief: "uitgaan", imperfectum: ["ging uit", "gingen uit"], perfectum: ["zijn", "uitgegaan"], translation: "going out"},
    {infinitief: "uittrekken", imperfectum: ["trok uit", "trokken uit"], perfectum: ["hebben", "uitgetrokken"], translation: "pull out"},
    {infinitief: "vallen", imperfectum: ["viel", "vielen"], perfectum: ["zijn", "gevallen"], translation: "to fall"},
    {infinitief: "varen", imperfectum: ["voer", "voeren"], perfectum: ["hebben/zijn", "gevaren"], translation: "sail"},
    {infinitief: "verbieden", imperfectum: ["verbood", "verboden"], perfectum: ["hebben", "verboden"], translation: "prohibit"},
    {infinitief: "vergeten", imperfectum: ["vergat", "vergaten"], perfectum: ["hebben", "vergeten"], translation: "to forget"},
    {infinitief: "verkopen", imperfectum: ["verkocht", "verkochten"], perfectum: ["hebben", "verkocht"], translation: "to sell"},
    {infinitief: "verliezen", imperfectum: ["verloor", "verloren"], perfectum: ["hebben", "verloren"], translation: "to lose"},
    {infinitief: "verstaan", imperfectum: ["verstond", "verstonden"], perfectum: ["hebben", "verstaan"], translation: "to hear"},
    {infinitief: "vertrekken", imperfectum: ["vertrok", "vertrokken"], perfectum: ["zijn", "vertrokken"], translation: "to leave"},
    {infinitief: "vervangen", imperfectum: ["verving", "vervingen"], perfectum: ["hebben", "vervangen"], translation: "to replace"},
    {infinitief: "vinden", imperfectum: ["vond", "vonden"], perfectum: ["hebben", "gevonden"], translation: "to find"},
    {infinitief: "vliegen", imperfectum: ["vloog", "vlogen"], perfectum: ["hebben/zijn", "gevlogen"], translation: "to fly"},
    {infinitief: "voorkomen", imperfectum: ["voorkwam", "voorkwamen"], perfectum: ["hebben", "voorkomen"], translation: "prevent"},
    {infinitief: "vragen", imperfectum: ["vroeg", "vroegen"], perfectum: ["hebben", "gevraagd"], translation: "to ask"},
    {infinitief: "vriezen", imperfectum: ["vroor", ""], perfectum: ["het heeft", "gevroren"], translation: "freeze"},
    {infinitief: "wassen", imperfectum: ["waste", "wasten"], perfectum: ["hebben", "gewassen"], translation: "to wash"},
    {infinitief: "wegen", imperfectum: ["woog", "wogen"], perfectum: ["hebben", "gewogen"], translation: "weigh"},
    {infinitief: "weten", imperfectum: ["wist", "wisten"], perfectum: ["hebben", "geweten"], translation: "know"},
    {infinitief: "wijzen", imperfectum: ["wees", "wezen"], perfectum: ["hebben", "gewezen"], translation: "ways"},
    {infinitief: "willen", imperfectum: ["wou", "wilde", "wilden"], perfectum: ["hebben", "gewild"], translation: "want"},
    {infinitief: "winnen", imperfectum: ["won", "wonnen"], perfectum: ["hebben", "gewonnen"], translation: "to win"},
    {infinitief: "worden", imperfectum: ["werd", "werden"], perfectum: ["zijn", "geworden"], translation: "become"},
    {infinitief: "zeggen", imperfectum: ["zei", "zeiden"], perfectum: ["hebben", "gezegd"], translation: "say"},
    {infinitief: "zien", imperfectum: ["zag", "zagen"], perfectum: ["hebben", "gezien"], translation: "to see"},
    {infinitief: "zijn", imperfectum: ["was", "waren"], perfectum: ["zijn", "geweest"], translation: "are"},
    {infinitief: "zingen", imperfectum: ["zong", "zongen"], perfectum: ["hebben", "gezongen"], translation: "to sing"},
    {infinitief: "zitten", imperfectum: ["zat", "zaten"], perfectum: ["hebben", "gezeten"], translation: "to sit"},
    {infinitief: "zoeken", imperfectum: ["zocht", "zochten"], perfectum: ["hebben", "gezocht"], translation: "to search"},
    {infinitief: "zullen", imperfectum: ["zou", "zouden"], perfectum: ["hebben", ""], translation: "shall"},
    {infinitief: "zwemmen", imperfectum: ["zwom", "zwommen"], perfectum: ["hebben/zijn", "gezwommen"], translation: "swimming"},
]